### PR TITLE
Enable election bundle home page and firstrun

### PR DESCRIPTION
**Pull request by craigcook**
This ended up being two separate switches, which is probably alright in the end because we could need to control these pages separately anyway.

We should verify stage before going to prod, and prod is due to flip at 6am Pacific.

Compare switch names in bedrock:
[home page](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/views.py#L190)
[firstrun](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L473)

https://github.com/mozilla/bedrock/issues/6186

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Names match. R+ ⚾️

**Comment by stephaniehobson** [comment]
Note: I told the funnel cake reviewers we would push the firstrun page live so they can test it. That's why the firstrun page switch is being flipped.

**Comment by alexgibson** [comment]
Is there no funnelcake config that needs pushing here?

**Comment by alexgibson** [comment]
Ok, it looks like there has been a last minute change (still reading up on Slack), and I don't see any funnelcake logic in the PR. So I'm guessing this is fine 👍 

I'm going to close this PR, and open two new ones so that we can test and verify on stage independently before a prod push.

**Pull request closed without merging**
