### PR TITLE
switch to using the sync workers

### PR DESCRIPTION
**Pull request by duallain**

### CODE REVIEW

**Comment by pmac** [comment]
shouldn't we do this on dev or stage first?

**Comment by duallain** [comment]
@pmac we could, wasn't sure if we wanted to only make the change for eks.  (Prod-fr is still currently the only eks bedrock deployment).

**Comment by pmac** [comment]
oh, are we not seeing the issue in the GCP cluster?

**Comment by duallain** [comment]
I don't believe so,  or at least that's the theory I've been working under.  Happy to try gcp dev/staging first if we want to go that way.

**Pull request merged**
