### PR TITLE
Refactering www-config test setup

### PR DESCRIPTION
**Pull request by duallain**
Using child pipelines to have a good encapsulation of each deployment pipeline.
This should hopefully make it clearer what we're testing.
And ensure that we test each deployment on each release.
Also includes a stub for running tests of the whole environment, chicken and egg problem with the tests, so a minimal stub made since for now I think.

### CODE REVIEW

**Comment by duallain** [comment]
Example pipeline - https://gitlab.com/mozmeao/www-config/-/pipelines/443051330

**Comment by alexgibson** [comment]
My 2 pence here:

- I think we can probably get rid of the manual test jobs, as these are not really used? (I'm also pretty sure the edge one isn't configured correctly to run?).
  - `test-chrome-saucelabs`
  - `test-download-saucelabs`
  - `test-edge-saucelabs`
  - `test-firefox-saucelabs`
- I agree on testing older browsers against the CDN, in particular IE. I am a bit wary on running functional tests against the CDN in general though, as we're almost sure to get bitten by cache when things in the pages change? Maybe we could set up some kind of CDN specific _sanity tests_ for key URLs, only to make sure old browsers get a valid 200 response instead?

**Comment by pmac** [comment]
Tests won't work against the CDN. We've never tested against the CDN also because the point is to be sure that the right things are being served up by the servers.

**Comment by alexgibson** [comment]
I do see value in CDN tests that just make sure the site can be loaded in old browsers. That’s something that often seems the biggest challenge these days when it comes to SSL certs?

**Comment by pmac** [comment]
> I do see value in CDN tests that just make sure the site can be loaded in old browsers. That’s something that often seems the biggest challenge these days when it comes to SSL certs?

Good point. A small set of tests that just ensure things load for this purpose would be good. Sounds more like something we should be running daily/weekly though, instead of only at deploy time. We've been thinking of doing more of that for some link checking and things.

**Comment by duallain** [comment]
I think we're all on the same page in regards to the old test suite not being a great way to test the cdn. Testing the deployments should stay largely the same. These are the changes I'm possibly making with this PR: 

- cleanup the manual jobs.
- Ensure that in prod we'll run against iowa and frankfurt every time, instead of picking one or the other
- (possibly, depending on feedback) remove ie/ie9 sanity from per deployment testing, move to per environment (more on that below)

How should we implement the 'cdn' tests?  I could add them to bedrock's existing pytest suite with a new mark keyword, or extend one of the tags we're already using (like headless/smoke/sanity).  Or could make a new folder of tests in either bedrock's git repo or here. Any/all are fine for me, I'll probably default to a new mark in the existing suite if there are no strong feelings otherwise.

I think splitting the ie tests to default to 'smoke' for each region we deploy, but putting 'sanity', for both ie9 and ie, at just the cdn makes the most sense to me. I think this matches both of your comments, testing ssl certs (per your comment @alexgibson ) via the cdn, but 'website functionality' per deployment. (I assume the css/js magic to work with all the various browsers is part of what you mean with "the point is to be sure that the right things are being served up by the servers" @pmac )

**Comment by alexgibson** [comment]
I think we should leave the `smoke` marker tests as-is. These test run against IE11 to ensure that page functionality still works at a basic level, which is still important for now.

I'm happy to sacrifice the `sanity` marker, if we move to testing IE9 against the CDN at a non-page specific level.

@duallain how do you plan to run these CDN tests - would you be using a real browser via saucelabs, or could they be headless and still give us confidence things work as we expect? I guess that migth decide what the marker should be.

**Comment by duallain** [comment]
Thank you for the answers Alex, I'll keep the smoke tests running against the deployments.  Makes perfect sense.

I'll keep both some real browser tests and some net-new headless tests. Don't want to overload the 'headless' tag, since it looks to run a good number of tests.  For the real browser tests, I'll run the sanity tests, we can add/remove tests as needed, either saucelabs or the selenium setup (remote) that Giorgos wrote with docker containers. I'll try the 'remote' setup first just to keep costs down, but I'm guessing saucelabs will be needed for ie9 specifically.

**Comment by alexgibson** [comment]
>  For the real browser tests, I'll run the sanity tests, we can add/remove tests as needed, either saucelabs or the selenium setup (remote) that Giorgos wrote with docker containers. I'll try the 'remote' setup first just to keep costs down, but I'm guessing saucelabs will be needed for ie9 specifically.

Yeah to test against Windows we need to run in saucelabs. Currently all the `sanify` marker tests are functional (they check for specific thing in certain pages), so it we're going to be repurposing those for the CDN then, we should probably do that before making this switch? Thoughts?

**Comment by duallain** [comment]
> > 
> 
> Yeah to test against Windows we need to run in saucelabs. Currently all the `sanity` marker tests are functional (they check for specific thing in certain pages), so it we're going to be repurposing those for the CDN then, we should probably do that before making this switch? Thoughts?

Open to suggestions or changes, but my intent was to do a small number of functional tests through the cdn with IE as a check.  I don't think those tests need to change much, just trying to load a few pages will likely catch most of the cdn issues. I don't think we've found many IE issues with the cdn that a single page load wouldn't discover.  I think this looks good right now, are you suggesting we add or remove some tests?

We're checking caching, image loading, locale redirects headlessly with the new test file over in the bedrock pr.  Hopefully all of the 'features' of the cdn get covered that way.

**Comment by alexgibson** [comment]
> Open to suggestions or changes, but my intent was to do a small number of functional tests through the cdn with IE as a check

Sorry if I'm a little lost over all the convo that's happened here and in bedrock. But I thought we were aligned on functional tests not being suitable for the CDN? Is your intent to use saucelabs for testing the CDN in IE, or some other method of service/testing?

**Comment by duallain** [comment]
> Edit: I guess what I want to be sure on is if we're moving IE9 tests to run against the CDN, we're no longer looking for certain things in the pages. Right now the `sanity` tests do things like make sure download buttons are visible. Maybe that's ok for now, but ideally I was hoping we could have a suite of CDN tests that aren't concerned about page content.

TBH I'm also a bit lost. Can you explain what you want me to do?

I'm reading your comments to mean that it'd be a nice to have for the ie/sanity tests to be changed to be less tightly coupled with the website content. That makes some sense to me, but I'm not sure I could come up with what the new tests ought to be.

It feels like 'sampling' the content of a few pages through the cdn puts us in a better position than not.  And I don't think I've really locked us into specific tests being ran, it can always be changed later, if someone who knows more has the time to make the change you're thinking about.

Is this PR alright right now? Is there something about the specific choices made that you'd like to see changed?

**Comment by alexgibson** [comment]
@duallain sorry for confusion - reading the discussion above it sounded like we were all aligned on not running functional tests against the CDN. However your latest suggestion seems to suggest this is what you want to move forward with? This is why I’m a bit confused.

My understanding was we were going to create some other suite of tests to run against the CDN instead of the current IE sanity tests. Apologies if that’s not what you meant, but like I said earlier in the convo I think long term we might hit caching issues here when page content changes.

We can move forward here I think to save getting stuck and merge. But the current sanity tests aren’t ideal long term to be run in this way imho. Happy to talk through this more in person if it helps.

**Comment by duallain** [comment]
I've removed all functional testing from the cdn. Also wrote the cdn tests to be on a schedule (though the schedule definition has to be done by hand).

**Pull request merged**
