### PR TITLE
Activate Pocket saves switch

### PR DESCRIPTION
**Pull request by maureenlholland**
Related to https://github.com/mozilla/bedrock/pull/12271

~Allows l10n translation before content change goes live Oct. 31~

DO NOT MERGE until ~Oct. 31~ Nov. 7 (must be coordinated with Pocket change)

### CODE REVIEW

**Review by alexgibson — APPROVED** [review]
r+ 

No changes should be needed here to allow L10n to happen prior to Oct 31 (as all switches default to `True` on dev?). But if it helps for folks to see things early on stage then this works too.

**Comment by maureenlholland** [comment]
Ah, good point! Will hold off on merge until Oct. 31

**Comment by maureenlholland** [comment]
delaying to Nov. 7

**Review by nathan-barrett — APPROVED** [review]
📓 ➡️ 💾

**Pull request merged**
