### PR TITLE
Prom emptydir

### PR DESCRIPTION
**Pull request by duallain**

### CODE REVIEW

**Comment by sciurus** [comment]
What is actually stored in the files in this directory? The current state of all the metrics being exported?

They're currently saved to a directory in the docker image's root filesystem, I think. And that filesystem (which uses [overlayfs](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) or something like that) is unique per running container and created/destroyed alongside it.

This shifts them to a directory on the host that is shared across all bedrock pods running on the host. Do you need to do anything to the folder permissions so that bedrock can write to it? Does that introduce any risks of multiple pods having clashing files here, or do we expect them to get unique names? What's your theory for how this might this reduce memory usage?

**Comment by duallain** [comment]
> Alan, I'm curious what's the hunch you have that makes you want to try this.
> 

In the stack trace, towards the end there's a section like - 

```
File "/venv/lib/python3.7/site-packages/prometheus_client/multiprocess.py", line 41, in merge
   metrics = MultiProcessCollector._read_metrics(files)
File "/venv/lib/python3.7/site-packages/prometheus_client/multiprocess.py", line 61, in _read_metrics
  file_values = MmapedDict.read_all_values_from_file(f)
File "/venv/lib/python3.7/site-packages/prometheus_client/mmap_dict.py", line 86, in read_all_values_from_file
  data = infp.read(mmap.PAGESIZE)
File "/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 192, in handle_abort
  sys.exit(1)
```

which seems like is an error complaining that there isn't enough memory space to aggregate the metrics.  Which probably implies the fix in this PR won't help.


> What is actually stored in the files in this directory? The current state of all the metrics being exported?
> 
My understanding is that the prom exporter in multiprocess mode stores 3 files per process (which are sqlite dbs it looks like) to store the various metrics.  Then when you query `/metrics` it aggregates the metrics in all the dbs before returning them.  

> They're currently saved to a directory in the docker image's root filesystem, I think, which uses [overlayfs](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) or something like that.
> 
> This shifts them to a directory on the host filesystem. Do you need to do anything to the folder permissions so that bedrock can write to it?

I tested this on dev, and it ended up working.  No file permission issues, and empty dir being coupled to pods it seemed to work fairly well from that perspective.

I am wondering if I'm just working on the wrong part of the problem.

**Comment by pmac** [comment]
I also worry that this would mean that the files would be written to by multiple pods on the same host as they're named for the process number, which should match across pods. We could probably customize the file names to fix this, but it would likely be an issue if we decide to go this way.

**Comment by duallain** [comment]
> I also worry that this would mean that the files would be written to by multiple pods on the same host as they're named for the process number, which should match across pods. We could probably customize the file names to fix this, but it would likely be an issue if we decide to go this way.

I think emptydir is 1-1 with pods rather than nodes, or at least that was why I choose it in this specific case.  (I think that's what the {} in the path implies).

**Pull request closed without merging**
